### PR TITLE
Transpose jacobian, and expand readme.

### PR DESCRIPTION
**Pull request by pkofod**

### CODE REVIEW

**Comment by cortner** [comment]
just out of curiosity: why did you change `;` to `,` in the array construction?

**Comment by cortner** [comment]
From the travis test it seems that it is now required that the constraint is an array and can no longer be a scalar. Can that be fixed easily? Otherwise maybe just fix the tests, merge and we can figure it out afterwards.

**Comment by cortner** [comment]
btw, the error on travis about scalars vs [] - I get that also on my local v0.5

**Comment by pkofod** [comment]
> just out of curiosity: why did you change ; to , in the array construction?

Well, I can change it back. It's just that `;` will call `vcat`, but `,` calls the `vect` function that directly copies the tuple into an empty array. To be honest, I think it makes absolutely no difference, I just didn't see it as concatenation, but as constructing something.

> From the travis test it seems that it is now required that the constraint is an array and can no longer be a scalar. Can that be fixed easily? Otherwise maybe just fix the tests, merge and we can figure it out afterwards.

I'll fix this before merging.

**Comment by cortner** [comment]
> > just out of curiosity: why did you change ; to , in the array construction?
> 
> Well, I can change it back. It's just that ; will call vcat, but , calls the vect function that directly copies the tuple into an empty array. To be honest, I think it makes absolutely no difference, I just didn't see it as concatenation, but as constructing something.

Thank you - I didn't actually know that yet. I'll need to do some reading

**Comment by pkofod** [comment]
> Thank you - I didn't actually know that yet. I'll need to do some reading

just to show you what I mean:

``` julia
julia> @which [1;2;3;4]
vcat{T<:Number}(X::T...) at abstractarray.jl:965

julia> @which [1,2,3,4]
vect{T}(X::T...) at abstractarray.jl:21
```

Here it doesn't make any difference, the resulting array is still a vector containing 1,2,3, and 4, but if the elements are vectors themselves, for example, it matters

``` julia
julia> [[1,1];[2,2];[3,3];[4,4]]
8-element Array{Int64,1}:
 1
 1
 2
 2
 3
 3
 4
 4

julia> [[1,1], [2,2], [3,3], [4,4]]
4-element Array{Array{Int64,1},1}:
 [1,1]
 [2,2]
 [3,3]
 [4,4]
```

**Pull request merged**
