### PR TITLE
Add ProjectedGradientDescent for bounds.

### PR DESCRIPTION
**Pull request by pkofod**
Just an experiment, don't merge. I still need to sort some things out. I also realize the refactor in Optim is not complete. I had to add too many qualifications (`Optim.`)  to my taste.

Notice, I wrote `BoundsConstraint` here, just to be annoying. Just wanted to see how it looked compared to the plural.

### CODE REVIEW

**Comment by pkofod** [comment]
Maybe `BoxContraint` instead? We can do an abstract `ConvexConstraint`. Then we could have `BoxConstraint <: ConvexConstraint`, but also a `BallConstraint <: ConvexConstraint` that would then have `project` dispatch to a version that does

```
function project!(x, bc::BallConstraint)
    for i = 1:length(x)
        x[i] = min(1, 1/norm(x[i]))*x[i]
    end
end
```

**Comment by cortner** [comment]
I prefer `BoxConstraint`; good idea to have both ball and box constraints.

**Comment by pkofod** [comment]
Okay, I decided to drop the plural `s` from the previous PR. I added a simple "ball" constraint. Basically, all subtypes of `ConvexConstraint` are meant to be simple convex constraints on the `x`s for use with projection methods. As a result, they require an implementation of `project!(X, constraint)` to work. I guess the next step is to try to layer them? Then we can, with slack variables, handle these new convex constraints, equality constraints, and also inequality constraints.

**Comment by cortner** [comment]
> Okay, I decided to drop the plural s from the previous PR. 

I think it is slightly more succinct. 

> I guess the next step is to try to layer them? Then we can, with slack variables, handle these new convex constraints, equality constraints, and also inequality constraints.

Yes, that would be my first approach. In principle this could be left to the user.

Thanks for all this; I am currently occupied with something else, but I now got my molecular simulation up to the point where I want to use the AL method. So I hope to get back to this code soon as I will need a preconditioned version :).

**Comment by cortner** [comment]
Btw, I'm happy for you to merge this whenever you think it is ready. 
- Re `ProjectedGradientDescent`: should the line-search perform a projection at each line-search step? This is a functionality that I need myself as well in the near future. It would essentially make for curved line search paths, but this is not a problem -- at least not for gradient-descent. For other methods (CG, LBFGS) it could cause problems, I am not sure how well this is already understood?
- Do the Box-constraints allow you to use [0, Inf] for the box? That would be useful for general inequality constraints.

**Comment by pkofod** [comment]
> So I hope to get back to this code soon as I will need a **preconditioned version**

I had a feeling this would come up! :)

**Comment by pkofod** [comment]
> Do the Box-constraints allow you to use [0, Inf] for the box? That would be useful for general inequality constraints.

Sure, the code looks like this:

``` julia
function project!(X, eqc::BoxConstraint)
    @inbounds for (i, x) in enumerate(X)
        X[i] = max(min(x, eqc.upper[i]), eqc.lower[i])
    end
end
```

So if `eqc.upper[i]` is `Inf`, the inner calculation will be `x`, and the outer calculation will then either be x or 0 if x is negative (or `-0.0` I guess...).

**Comment by pkofod** [comment]
> Re ProjectedGradientDescent: should the line-search perform a projection at each line-search step? This is a functionality that I need myself as well in the near future. It would essentially make for curved line search paths, but this is not a problem -- at least not for gradient-descent. For other methods (CG, LBFGS) it could cause problems, I am not sure how well this is already understood?

I am intending to implement projected LBFGS as well, but I have not yet looked into this. I basically took the "safe choice" with (preconditioned) projected gradient descent with a projection step on the step vector that makes sure it stops at the boundary of the box, and then a backtracking line search default, such that we always stay inside the box in the line search step. We could do more advanced stuff as well, but I think the most predictable default behaviour is the current one.

**Comment by cortner** [comment]
perfect

Though maybe for the future it would be useful to incorporate the projection steps into the main `Optim.jl` code rather than rewriting each of them?

**Comment by pkofod** [comment]
> Though maybe for the future it would be useful to incorporate the projection steps into the main Optim.jl code rather than rewriting each of them?

Yes, Levenberg-Marquardt already has a projection step for the box constraints, so we should just factor that out, and reuse it here. I'm sort of considering this package a sort of playground right now, and hopefully it will become clearer and clearer what should go into Optim (maybe everything?) and what shouldn't.

**Comment by cortner** [comment]
that sounds good for me!

I also want to experiment with CG and LBFGS in manifolds (this is useful if an equality constraint can implement a simple projection step) and if you are ok will also put this in here.

**Comment by pkofod** [comment]
As in finding min_{x in M} f(x) where `M` is some manifold? Sure!

**Pull request merged**
