### PR TITLE
EqualityConstraints added.

### PR DESCRIPTION
**Pull request by pkofod**
The field names are a bit weird perhaps, but would something like this work? I'll try to add bounds constraints later.

### CODE REVIEW

**Comment by cortner** [comment]
that works for me. With two suggestions: 
- `EqualityConstraint` instead of plural (not 100% sure about this one)
- provide a constructor to pass `Jc` instead of `Jc!`; actually this should maybe be done in `Optim.jl` as well. I find myself writing `(x, g) -> copy!(g, my grad(x))` quite a lot .

**Comment by cortner** [comment]
I've been thinking about `LinearEqualityConstraint`: this should be fairly straightforward to implement but not within the AL framework, but simply by projecting the entire problem onto the affine subspace. How important are linear  / affine equality constraints in general?

**Comment by pkofod** [comment]
> EqualityConstraint instead of plural (not 100% sure about this one)

The only reason why I made it plural is because `c` can represent many constraints at once. I can go either way.

**Comment by cortner** [comment]
What does nocedal/Wright say?

**Comment by pkofod** [comment]
> What does nocedal/Wright say?

say about what? the plural-thing?

**Comment by pkofod** [comment]
> provide a constructor to pass Jc instead of Jc!; actually this should maybe be done in Optim.jl as well. I find myself writing (x, g) -> copy!(g, my grad(x)) quite a lot .

How would that be different from the one that passes the mutating version?

**Comment by cortner** [comment]
> > What does nocedal/Wright say?
> 
> say about what? the plural-thing?

NW seems unclear about - let's just stick with plural as you started it. Please feel free to merge.

**Comment by cortner** [comment]
> > provide a constructor to pass Jc instead of Jc!; actually this should maybe be done in Optim.jl as well. I find myself writing (x, g) -> copy!(g, my grad(x)) quite a lot .
> 
> How would that be different from the one that passes the mutating version?

`DifferentiableFunction(f=f, g=g) = DifferentiableFunction(f, g! = (x,gg) -> copy!(gg, g(x))`

**Comment by pkofod** [comment]
> DifferentiableFunction(f=f, g=g) = DifferentiableFunction(f, g! = (x,gg) -> copy!(gg, g(x))

Of course! The only problem is https://github.com/JuliaOpt/Optim.jl/issues/285

**Pull request merged**
